/* MLton 20180207 */
/*   created this file on Sat Dec 01 01:26:25 2018. */
/* Do not edit this file. */
/* Flag settings:  */
/*    align: 8 */
/*    atMLtons: (@MLton, --) */
/*    chunk: chunk per function */
/*    closureConvertGlobalize: true */
/*    closureConvertShrink: true */
/*    codegen: amd64 */
/*    contifyIntoMain: false */
/*    debug: false */
/*    defaultChar: char8 */
/*    defaultWideChar: widechar32 */
/*    defaultInt: int32 */
/*    defaultReal: real64 */
/*    defaultWord: word32 */
/*    diag passes: [] */
/*    execute passes: [] */
/*    elaborate allowConstant (default): false */
/*    elaborate allowConstant (enabled): true */
/*    elaborate allowFFI (default): false */
/*    elaborate allowFFI (enabled): true */
/*    elaborate allowPrim (default): false */
/*    elaborate allowPrim (enabled): true */
/*    elaborate allowOverload (default): false */
/*    elaborate allowOverload (enabled): true */
/*    elaborate allowRedefineSpecialIds (default): false */
/*    elaborate allowRedefineSpecialIds (enabled): true */
/*    elaborate allowSpecifySpecialIds (default): false */
/*    elaborate allowSpecifySpecialIds (enabled): true */
/*    elaborate deadCode (default): false */
/*    elaborate deadCode (enabled): true */
/*    elaborate forceUsed (default): false */
/*    elaborate forceUsed (enabled): true */
/*    elaborate ffiStr (default):  */
/*    elaborate ffiStr (enabled): true */
/*    elaborate nonexhaustiveBind (default): warn */
/*    elaborate nonexhaustiveBind (enabled): true */
/*    elaborate nonexhaustiveExnBind (default): default */
/*    elaborate nonexhaustiveExnBind (enabled): true */
/*    elaborate redundantBind (default): warn */
/*    elaborate redundantBind (enabled): true */
/*    elaborate nonexhaustiveMatch (default): warn */
/*    elaborate nonexhaustiveMatch (enabled): true */
/*    elaborate nonexhaustiveExnMatch (default): default */
/*    elaborate nonexhaustiveExnMatch (enabled): true */
/*    elaborate redundantMatch (default): warn */
/*    elaborate redundantMatch (enabled): true */
/*    elaborate nonexhaustiveRaise (default): ignore */
/*    elaborate nonexhaustiveRaise (enabled): true */
/*    elaborate nonexhaustiveExnRaise (default): ignore */
/*    elaborate nonexhaustiveExnRaise (enabled): true */
/*    elaborate redundantRaise (default): warn */
/*    elaborate redundantRaise (enabled): true */
/*    elaborate resolveScope (default): strdec */
/*    elaborate resolveScope (enabled): true */
/*    elaborate sequenceNonUnit (default): ignore */
/*    elaborate sequenceNonUnit (enabled): true */
/*    elaborate valrecConstr (default): warn */
/*    elaborate valrecConstr (enabled): true */
/*    elaborate warnUnused (default): false */
/*    elaborate warnUnused (enabled): true */
/*    elaborate allowDoDecls (default): false */
/*    elaborate allowDoDecls (enabled): true */
/*    elaborate allowExtendedNumConsts (default): false */
/*    elaborate allowExtendedNumConsts (enabled): true */
/*    elaborate allowExtendedTextConsts (default): false */
/*    elaborate allowExtendedTextConsts (enabled): true */
/*    elaborate allowLineComments (default): false */
/*    elaborate allowLineComments (enabled): true */
/*    elaborate allowOptBar (default): false */
/*    elaborate allowOptBar (enabled): true */
/*    elaborate allowOptSemicolon (default): false */
/*    elaborate allowOptSemicolon (enabled): true */
/*    elaborate allowOrPats (default): false */
/*    elaborate allowOrPats (enabled): true */
/*    elaborate allowRecordPunExps (default): false */
/*    elaborate allowRecordPunExps (enabled): true */
/*    elaborate allowSigWithtype (default): false */
/*    elaborate allowSigWithtype (enabled): true */
/*    elaborate allowVectorExps (default): false */
/*    elaborate allowVectorExps (enabled): true */
/*    elaborate allowVectorPats (default): false */
/*    elaborate allowVectorPats (enabled): true */
/*    elaborate only: false */
/*    emit main: true */
/*    export header: None */
/*    exn history: false */
/*    generated output format: executable */
/*    gc check: Limit */
/*    indentation: 3 */
/*    inlineIntoMain: true */
/*    inlineLeafA: {loops = true, repeat = true, size = Some 20} */
/*    inlineLeafB: {loops = true, repeat = true, size = Some 40} */
/*    inlineNonRec: {small = 60, product = 320} */
/*    input file: vecdotvec */
/*    keep AST: false */
/*    keep CoreML: false */
/*    keep def use: true */
/*    keep dot: false */
/*    keep Machine: false */
/*    keep passes: [] */
/*    keep RSSA: false */
/*    keep SSA: false */
/*    keep SSA2: false */
/*    keep SXML: false */
/*    keep XML: false */
/*    extra_: false */
/*    lib dir: /usr/local/lib/mlton */
/*    lib target dir: /usr/local/lib/mlton/targets/self */
/*    loop ssa passes: 1 */
/*    loop ssa2 passes: 1 */
/*    loop unrolling limit: 150 */
/*    loop unswitching limit: 300 */
/*    mark cards: true */
/*    max function size: 10000 */
/*    mlb path vars: [{var = SML_LIB, path = $(LIB_MLTON_DIR)/sml}] */
/*    native commented: 0 */
/*    native live stack: false */
/*    native optimize: 1 */
/*    native move hoist: true */
/*    native copy prop: true */
/*    native copy prop cutoff: 1000 */
/*    native cutoff: 100 */
/*    native live transfer: 8 */
/*    native shuffle: true */
/*    native ieee fp: false */
/*    native split: Some 20000 */
/*    optFuel: None */
/*    optimizationPasses: [<ssa2::default>, <ssa::default>, <sxml::default>, <xml::default>] */
/*    polyvariance: Some {hofo = true, rounds = 2, small = 30, product = 300} */
/*    prefer abs paths: false */
/*    prof passes: [] */
/*    profile: None */
/*    profile branch: false */
/*    profile C: [] */
/*    profile IL: ProfileSource */
/*    profile include/exclude: [(Seq [Star [.], Or [Seq [Seq [[$], [(], [S], [M], [L], [_], [L], [I], [B], [)]]]], Star [.]], false)] */
/*    profile raise: false */
/*    profile stack: false */
/*    profile val: false */
/*    show basis: None */
/*    show basis compact: false */
/*    show basis def: true */
/*    show basis flat: true */
/*    show def-use: None */
/*    show types: true */
/*    target: self */
/*    target arch: AMD64 */
/*    target OS: Linux */
/*    type check: false */
/*    verbosity: Silent */
/*    warn unrecognized annotation: true */
/*    warn deprecated features: true */
/*    zone cut depth: 100 */
#include <amd64-main.h>

PRIVATE struct GC_state gcState;
PRIVATE CPointer globalCPointer [0];
PRIVATE CPointer CReturnQ;
PRIVATE Int8 globalInt8 [0];
PRIVATE Int8 CReturnI8;
PRIVATE Int16 globalInt16 [0];
PRIVATE Int16 CReturnI16;
PRIVATE Int32 globalInt32 [0];
PRIVATE Int32 CReturnI32;
PRIVATE Int64 globalInt64 [0];
PRIVATE Int64 CReturnI64;
PRIVATE Objptr globalObjptr [153];
PRIVATE Objptr CReturnP;
PRIVATE Real32 globalReal32 [0];
PRIVATE Real32 CReturnR32;
PRIVATE Real64 globalReal64 [6];
PRIVATE Real64 CReturnR64;
PRIVATE Word8 globalWord8 [0];
PRIVATE Word8 CReturnW8;
PRIVATE Word16 globalWord16 [0];
PRIVATE Word16 CReturnW16;
PRIVATE Word32 globalWord32 [0];
PRIVATE Word32 CReturnW32;
PRIVATE Word64 globalWord64 [0];
PRIVATE Word64 CReturnW64;
PRIVATE Pointer globalObjptrNonRoot [1];
PRIVATE Pointer MLton_FFI_opArgsResPtr;
static int saveGlobals (FILE *f) {
	SaveArray (globalCPointer, f);
	SaveArray (globalInt8, f);
	SaveArray (globalInt16, f);
	SaveArray (globalInt32, f);
	SaveArray (globalInt64, f);
	SaveArray (globalObjptr, f);
	SaveArray (globalReal32, f);
	SaveArray (globalReal64, f);
	SaveArray (globalWord8, f);
	SaveArray (globalWord16, f);
	SaveArray (globalWord32, f);
	SaveArray (globalWord64, f);
	return 0;
}
static int loadGlobals (FILE *f) {
	LoadArray (globalCPointer, f);
	LoadArray (globalInt8, f);
	LoadArray (globalInt16, f);
	LoadArray (globalInt32, f);
	LoadArray (globalInt64, f);
	LoadArray (globalObjptr, f);
	LoadArray (globalReal32, f);
	LoadArray (globalReal64, f);
	LoadArray (globalWord8, f);
	LoadArray (globalWord16, f);
	LoadArray (globalWord32, f);
	LoadArray (globalWord64, f);
	return 0;
}
BeginVectorInits
VectorInitElem (1, 75, 5, (pointer)"nostr")
VectorInitElem (1, 25, 12, (pointer)"addrnotavail")
VectorInitElem (1, 151, 2, (pointer)" [")
VectorInitElem (1, 69, 6, (pointer)"nolink")
VectorInitElem (1, 30, 6, (pointer)"badmsg")
VectorInitElem (1, 147, 4, (pointer)"Io: ")
VectorInitElem (1, 57, 8, (pointer)"multihop")
VectorInitElem (1, 123, 6, (pointer)"Option")
VectorInitElem (1, 23, 5, (pointer)"acces")
VectorInitElem (1, 72, 10, (pointer)"noprotoopt")
VectorInitElem (1, 44, 11, (pointer)"hostunreach")
VectorInitElem (1, 35, 11, (pointer)"connrefused")
VectorInitElem (1, 104, 17, (pointer)"Sequence.fromList")
VectorInitElem (1, 143, 3, (pointer)"inf")
VectorInitElem (1, 56, 7, (pointer)"msgsize")
VectorInitElem (1, 112, 1, (pointer)"\n")
VectorInitElem (1, 45, 4, (pointer)"idrm")
VectorInitElem (1, 27, 5, (pointer)"again")
VectorInitElem (1, 148, 6, (pointer)"Fail: ")
VectorInitElem (1, 48, 4, (pointer)"intr")
VectorInitElem (1, 79, 8, (pointer)"notempty")
VectorInitElem (1, 73, 5, (pointer)"nospc")
VectorInitElem (1, 53, 4, (pointer)"loop")
VectorInitElem (1, 102, 1, (pointer)"]")
VectorInitElem (1, 140, 1, (pointer)"~")
VectorInitElem (1, 142, 4, (pointer)"~inf")
VectorInitElem (1, 40, 5, (pointer)"dquot")
VectorInitElem (1, 24, 9, (pointer)"addrinuse")
VectorInitElem (1, 100, 10, (pointer)"wouldblock")
VectorInitElem (1, 99, 6, (pointer)"txtbsy")
VectorInitElem (1, 76, 5, (pointer)"nosys")
VectorInitElem (1, 83, 4, (pointer)"nxio")
VectorInitElem (1, 94, 4, (pointer)"srch")
VectorInitElem (1, 92, 4, (pointer)"rofs")
VectorInitElem (1, 47, 10, (pointer)"inprogress")
VectorInitElem (1, 60, 8, (pointer)"netreset")
VectorInitElem (1, 41, 5, (pointer)"exist")
VectorInitElem (1, 137, 16, (pointer)"0123456789ABCDEF")
VectorInitElem (1, 65, 5, (pointer)"nodev")
VectorInitElem (1, 81, 6, (pointer)"notsup")
VectorInitElem (1, 139, 2, (pointer)"0.")
VectorInitElem (1, 34, 11, (pointer)"connaborted")
VectorInitElem (1, 85, 8, (pointer)"overflow")
VectorInitElem (1, 89, 14, (pointer)"protonosupport")
VectorInitElem (1, 49, 5, (pointer)"inval")
VectorInitElem (1, 31, 4, (pointer)"busy")
VectorInitElem (1, 126, 3, (pointer)"[| ")
VectorInitElem (1, 59, 7, (pointer)"netdown")
VectorInitElem (1, 115, 5, (pointer)"Fail ")
VectorInitElem (1, 120, 8, (pointer)"Overflow")
VectorInitElem (1, 95, 5, (pointer)"stale")
VectorInitElem (1, 93, 5, (pointer)"spipe")
VectorInitElem (1, 39, 3, (pointer)"dom")
VectorInitElem (1, 64, 6, (pointer)"nodata")
VectorInitElem (1, 150, 9, (pointer)"<UNKNOWN>")
VectorInitElem (1, 67, 6, (pointer)"noexec")
VectorInitElem (1, 26, 11, (pointer)"afnosupport")
VectorInitElem (1, 46, 5, (pointer)"ilseq")
VectorInitElem (1, 131, 35, (pointer)"Top-level suffix raised exception.\n")
VectorInitElem (1, 88, 5, (pointer)"proto")
VectorInitElem (1, 134, 8, (pointer)"flushOut")
VectorInitElem (1, 105, 16, (pointer)"Thread.atomicEnd")
VectorInitElem (1, 127, 2, (pointer)", ")
VectorInitElem (1, 152, 16, (pointer)"MLton.Exit.exit(")
VectorInitElem (1, 117, 4, (pointer)"Fail")
VectorInitElem (1, 55, 5, (pointer)"mlink")
VectorInitElem (1, 43, 4, (pointer)"fbig")
VectorInitElem (1, 77, 7, (pointer)"notconn")
VectorInitElem (1, 107, 29, (pointer)"IEEEReal.RoundingMode.fromInt")
VectorInitElem (1, 109, 32, (pointer)"exit must have 0 <= status < 256")
VectorInitElem (1, 141, 3, (pointer)"nan")
VectorInitElem (1, 125, 8, (pointer)"<stdout>")
VectorInitElem (1, 149, 8, (pointer)"SysErr: ")
VectorInitElem (1, 74, 4, (pointer)"nosr")
VectorInitElem (1, 136, 1, (pointer)".")
VectorInitElem (1, 145, 14, (pointer)"\" failed with ")
VectorInitElem (1, 87, 4, (pointer)"pipe")
VectorInitElem (1, 144, 5, (pointer)"Fail8")
VectorInitElem (1, 118, 6, (pointer)"SysErr")
VectorInitElem (1, 113, 28, (pointer)"control shouldn\'t reach here")
VectorInitElem (1, 121, 4, (pointer)"Size")
VectorInitElem (1, 37, 6, (pointer)"deadlk")
VectorInitElem (1, 82, 5, (pointer)"notty")
VectorInitElem (1, 51, 6, (pointer)"isconn")
VectorInitElem (1, 33, 5, (pointer)"child")
VectorInitElem (1, 91, 5, (pointer)"range")
VectorInitElem (1, 62, 5, (pointer)"nfile")
VectorInitElem (1, 106, 15, (pointer)"Sequence.length")
VectorInitElem (1, 58, 11, (pointer)"nametoolong")
VectorInitElem (1, 128, 36, (pointer)"Top-level handler raised exception.\n")
VectorInitElem (1, 129, 3, (pointer)"|]\n")
VectorInitElem (1, 28, 7, (pointer)"already")
VectorInitElem (1, 90, 9, (pointer)"prototype")
VectorInitElem (1, 42, 5, (pointer)"fault")
VectorInitElem (1, 133, 6, (pointer)"output")
VectorInitElem (1, 70, 5, (pointer)"nomem")
VectorInitElem (1, 32, 8, (pointer)"canceled")
VectorInitElem (1, 68, 5, (pointer)"nolck")
VectorInitElem (1, 71, 5, (pointer)"nomsg")
VectorInitElem (1, 146, 2, (pointer)" \"")
VectorInitElem (1, 124, 12, (pointer)"ClosedStream")
VectorInitElem (1, 111, 21, (pointer)"MLton.Exit.wrapSuffix")
VectorInitElem (1, 103, 19, (pointer)"Sequence.Slice.base")
VectorInitElem (1, 36, 9, (pointer)"connreset")
VectorInitElem (1, 54, 5, (pointer)"mfile")
VectorInitElem (1, 66, 5, (pointer)"noent")
VectorInitElem (1, 38, 11, (pointer)"destaddrreq")
VectorInitElem (1, 116, 36, (pointer)"unhandled exception in Basis Library")
VectorInitElem (1, 132, 13, (pointer)"Unknown error")
VectorInitElem (1, 97, 8, (pointer)"timedout")
VectorInitElem (1, 29, 4, (pointer)"badf")
VectorInitElem (1, 50, 2, (pointer)"io")
VectorInitElem (1, 86, 4, (pointer)"perm")
VectorInitElem (1, 108, 13, (pointer)"partial write")
VectorInitElem (1, 101, 4, (pointer)"xdev")
VectorInitElem (1, 135, 0, (pointer)"")
VectorInitElem (1, 63, 6, (pointer)"nobufs")
VectorInitElem (1, 119, 2, (pointer)"Io")
VectorInitElem (1, 122, 9, (pointer)"Subscript")
VectorInitElem (1, 114, 21, (pointer)"unhandled exception: ")
VectorInitElem (1, 78, 6, (pointer)"notdir")
VectorInitElem (1, 61, 10, (pointer)"netunreach")
VectorInitElem (1, 138, 1, (pointer)"E")
VectorInitElem (1, 130, 9, (pointer)"result = ")
VectorInitElem (1, 110, 3, (pointer)"): ")
VectorInitElem (1, 98, 6, (pointer)"toobig")
VectorInitElem (1, 96, 4, (pointer)"time")
VectorInitElem (1, 84, 9, (pointer)"opnotsupp")
VectorInitElem (1, 80, 7, (pointer)"notsock")
VectorInitElem (1, 52, 5, (pointer)"isdir")
EndVectorInits
static void real_Init() {
	globalReal64[4] = 0.1E1;
	globalReal64[5] = 0.0;
	globalReal64[0] = 0.5E1;
	globalReal64[1] = 0.4E1;
	globalReal64[2] = 0.3E1;
	globalReal64[3] = 0.2E1;
}
static uint16_t frameOffsets0[] = {0};
static uint16_t frameOffsets1[] = {4,16,24,32,40};
static uint16_t frameOffsets2[] = {5,16,24,32,40,48};
static uint16_t frameOffsets3[] = {6,16,24,32,40,48,56};
static uint16_t frameOffsets4[] = {7,16,24,32,40,48,56,72};
static uint16_t frameOffsets5[] = {12,16,24,32,40,48,56,64,72,80,88,104,112};
static uint16_t frameOffsets6[] = {9,16,24,40,48,56,64,72,80,88};
static uint16_t frameOffsets7[] = {7,32,40,48,56,72,80,96};
static uint16_t frameOffsets8[] = {8,24,32,40,48,56,72,80,96};
static uint16_t frameOffsets9[] = {9,24,32,40,48,56,72,80,88,96};
static uint16_t frameOffsets10[] = {10,24,32,40,48,56,72,80,88,96,112};
static uint16_t frameOffsets11[] = {10,24,32,40,48,56,72,80,88,96,128};
static uint16_t frameOffsets12[] = {1,16};
static uint16_t frameOffsets13[] = {2,16,24};
static uint16_t frameOffsets14[] = {10,24,32,40,48,56,72,80,88,96,120};
static uint16_t frameOffsets15[] = {10,24,32,40,48,56,72,80,88,96,136};
static uint16_t frameOffsets16[] = {3,32,40,96};
static uint16_t frameOffsets17[] = {4,16,32,40,96};
static uint16_t frameOffsets18[] = {5,16,32,40,48,96};
static uint16_t frameOffsets19[] = {4,32,40,48,96};
static uint16_t frameOffsets20[] = {2,40,96};
static uint16_t frameOffsets21[] = {10,16,24,32,40,48,56,64,72,80,88};
static uint16_t frameOffsets22[] = {11,16,24,32,40,48,56,64,72,80,88,96};
static uint16_t frameOffsets23[] = {1,40};
static uint16_t frameOffsets24[] = {10,16,32,40,48,56,64,72,80,88,104};
static uint16_t frameOffsets25[] = {11,16,24,32,40,48,56,64,72,80,88,104};
static uint16_t frameOffsets26[] = {7,16,24,32,40,48,56,64};
static uint16_t frameOffsets27[] = {3,16,24,32};
static uint16_t frameOffsets28[] = {4,0,8,32,40};
static uint16_t frameOffsets29[] = {1,32};
static uint16_t frameOffsets30[] = {2,32,48};
static uint16_t frameOffsets31[] = {5,0,8,32,56,80};
static uint16_t frameOffsets32[] = {1,0};
static uint16_t frameOffsets33[] = {2,0,8};
static uint16_t frameOffsets34[] = {2,0,32};
static uint16_t frameOffsets35[] = {1,8};
static uint16_t frameOffsets36[] = {3,0,8,48};
static uint16_t frameOffsets37[] = {2,8,48};
static uint16_t frameOffsets38[] = {4,0,8,48,56};
static uint16_t frameOffsets39[] = {5,0,8,32,48,56};
static uint16_t frameOffsets40[] = {1,24};
static uint16_t frameOffsets41[] = {9,0,8,16,24,32,40,48,56,72};
static uint16_t frameOffsets42[] = {9,0,8,24,32,40,48,56,72,96};
static uint16_t frameOffsets43[] = {6,8,24,32,40,48,56};
static uint16_t frameOffsets44[] = {3,24,32,40};
static uint16_t frameOffsets45[] = {4,0,24,32,40};
static uint16_t frameOffsets46[] = {5,0,24,32,40,56};
static uint16_t frameOffsets47[] = {3,0,16,40};
static uint16_t frameOffsets48[] = {3,8,16,40};
static uint16_t frameOffsets49[] = {4,0,16,32,40};
static uint16_t frameOffsets50[] = {5,0,16,32,40,48};
static uint16_t frameOffsets51[] = {4,8,16,32,40};
static uint16_t frameOffsets52[] = {4,0,8,16,40};
static uint16_t frameOffsets53[] = {3,0,24,40};
static uint16_t frameOffsets54[] = {4,0,16,24,40};
static uint16_t frameOffsets55[] = {4,8,16,24,40};
static uint16_t frameOffsets56[] = {2,24,40};
static uint16_t frameOffsets57[] = {5,0,8,16,24,40};
static uint16_t frameOffsets58[] = {2,0,40};
static uint16_t frameOffsets59[] = {3,8,24,40};
static uint16_t frameOffsets60[] = {4,0,8,24,40};
static uint16_t frameOffsets61[] = {2,8,40};
static uint16_t frameOffsets62[] = {3,16,32,40};
static uint16_t frameOffsets63[] = {5,0,8,16,32,40};
static uint16_t frameOffsets64[] = {6,0,16,24,32,40,48};
static uint16_t frameOffsets65[] = {7,0,8,24,32,40,48,56};
static uint16_t frameOffsets66[] = {10,0,8,16,24,32,40,48,56,72,96};
static uint16_t frameOffsets67[] = {8,0,8,24,32,40,48,56,72};
static uint16_t frameOffsets68[] = {6,8,16,24,32,40,48};
static uint16_t frameOffsets69[] = {4,8,16,24,32};
static uint16_t frameOffsets70[] = {2,8,16};
static uint16_t frameOffsets71[] = {2,8,32};
static uint16_t frameOffsets72[] = {3,0,8,32};
static uint16_t frameOffsets73[] = {2,8,56};
static uint16_t frameOffsets74[] = {3,8,40,56};
static struct GC_frameLayout frameLayouts[] = {
	{C_FRAME, frameOffsets0, 8},
	{ML_FRAME, frameOffsets0, 8},
	{C_FRAME, frameOffsets1, 56},
	{C_FRAME, frameOffsets2, 64},
	{C_FRAME, frameOffsets3, 72},
	{C_FRAME, frameOffsets4, 88},
	{C_FRAME, frameOffsets5, 128},
	{C_FRAME, frameOffsets6, 104},
	{C_FRAME, frameOffsets7, 112},
	{C_FRAME, frameOffsets8, 112},
	{ML_FRAME, frameOffsets9, 112},
	{ML_FRAME, frameOffsets9, 120},
	{C_FRAME, frameOffsets10, 136},
	{C_FRAME, frameOffsets11, 144},
	{ML_FRAME, frameOffsets12, 32},
	{ML_FRAME, frameOffsets0, 24},
	{C_FRAME, frameOffsets13, 40},
	{ML_FRAME, frameOffsets9, 128},
	{C_FRAME, frameOffsets14, 144},
	{C_FRAME, frameOffsets15, 152},
	{ML_FRAME, frameOffsets16, 112},
	{C_FRAME, frameOffsets17, 112},
	{C_FRAME, frameOffsets18, 112},
	{C_FRAME, frameOffsets19, 112},
	{ML_FRAME, frameOffsets20, 112},
	{C_FRAME, frameOffsets21, 104},
	{C_FRAME, frameOffsets22, 112},
	{C_FRAME, frameOffsets0, 48},
	{C_FRAME, frameOffsets23, 56},
	{C_FRAME, frameOffsets0, 32},
	{C_FRAME, frameOffsets24, 120},
	{C_FRAME, frameOffsets25, 120},
	{C_FRAME, frameOffsets5, 144},
	{C_FRAME, frameOffsets26, 80},
	{C_FRAME, frameOffsets27, 48},
	{C_FRAME, frameOffsets1, 64},
	{C_FRAME, frameOffsets1, 72},
	{C_FRAME, frameOffsets0, 24},
	{ML_FRAME, frameOffsets28, 56},
	{C_FRAME, frameOffsets29, 56},
	{C_FRAME, frameOffsets30, 64},
	{C_FRAME, frameOffsets29, 48},
	{C_FRAME, frameOffsets31, 96},
	{ML_FRAME, frameOffsets32, 40},
	{C_FRAME, frameOffsets33, 40},
	{C_FRAME, frameOffsets28, 56},
	{C_FRAME, frameOffsets34, 48},
	{C_FRAME, frameOffsets35, 80},
	{C_FRAME, frameOffsets36, 80},
	{C_FRAME, frameOffsets37, 80},
	{C_FRAME, frameOffsets38, 88},
	{C_FRAME, frameOffsets39, 104},
	{C_FRAME, frameOffsets40, 40},
	{C_FRAME, frameOffsets0, 16},
	{C_FRAME, frameOffsets33, 24},
	{ML_FRAME, frameOffsets3, 72},
	{C_FRAME, frameOffsets41, 104},
	{C_FRAME, frameOffsets42, 112},
	{ML_FRAME, frameOffsets43, 72},
	{ML_FRAME, frameOffsets44, 56},
	{C_FRAME, frameOffsets45, 64},
	{C_FRAME, frameOffsets46, 72},
	{C_FRAME, frameOffsets47, 56},
	{C_FRAME, frameOffsets48, 56},
	{C_FRAME, frameOffsets49, 72},
	{C_FRAME, frameOffsets50, 72},
	{C_FRAME, frameOffsets51, 56},
	{C_FRAME, frameOffsets52, 64},
	{C_FRAME, frameOffsets53, 56},
	{C_FRAME, frameOffsets54, 56},
	{C_FRAME, frameOffsets55, 56},
	{ML_FRAME, frameOffsets56, 56},
	{C_FRAME, frameOffsets57, 56},
	{C_FRAME, frameOffsets58, 56},
	{C_FRAME, frameOffsets59, 56},
	{ML_FRAME, frameOffsets23, 56},
	{C_FRAME, frameOffsets60, 56},
	{C_FRAME, frameOffsets61, 56},
	{C_FRAME, frameOffsets62, 64},
	{C_FRAME, frameOffsets51, 64},
	{C_FRAME, frameOffsets63, 56},
	{C_FRAME, frameOffsets49, 64},
	{C_FRAME, frameOffsets64, 88},
	{C_FRAME, frameOffsets64, 72},
	{C_FRAME, frameOffsets65, 72},
	{C_FRAME, frameOffsets66, 112},
	{C_FRAME, frameOffsets67, 88},
	{C_FRAME, frameOffsets68, 64},
	{C_FRAME, frameOffsets69, 48},
	{C_FRAME, frameOffsets70, 32},
	{C_FRAME, frameOffsets32, 16},
	{ML_FRAME, frameOffsets71, 48},
	{ML_FRAME, frameOffsets0, 40},
	{C_FRAME, frameOffsets72, 48},
	{C_FRAME, frameOffsets32, 40},
	{ML_FRAME, frameOffsets35, 40},
	{C_FRAME, frameOffsets35, 40},
	{C_FRAME, frameOffsets61, 64},
	{C_FRAME, frameOffsets73, 72},
	{C_FRAME, frameOffsets74, 72},
	{C_FRAME, frameOffsets35, 48},
	{C_FRAME, frameOffsets71, 48},
};
static struct GC_objectType objectTypes[] = {
	{ STACK_TAG, FALSE, 0, 0 },
	{ NORMAL_TAG, TRUE, 16, 1 },
	{ WEAK_TAG, FALSE, 16, 0 },
	{ ARRAY_TAG, FALSE, 1, 0 },
	{ ARRAY_TAG, FALSE, 4, 0 },
	{ ARRAY_TAG, FALSE, 2, 0 },
	{ ARRAY_TAG, FALSE, 8, 0 },
	{ NORMAL_TAG, TRUE, 0, 1 },
	{ NORMAL_TAG, FALSE, 16, 0 },
	{ NORMAL_TAG, FALSE, 16, 1 },
	{ NORMAL_TAG, TRUE, 8, 0 },
	{ ARRAY_TAG, TRUE, 1, 0 },
	{ NORMAL_TAG, TRUE, 8, 0 },
	{ NORMAL_TAG, TRUE, 8, 0 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 3 },
	{ NORMAL_TAG, TRUE, 0, 1 },
	{ NORMAL_TAG, TRUE, 0, 0 },
	{ NORMAL_TAG, FALSE, 0, 4 },
	{ NORMAL_TAG, FALSE, 8, 1 },
	{ NORMAL_TAG, TRUE, 0, 1 },
	{ NORMAL_TAG, FALSE, 16, 0 },
	{ ARRAY_TAG, TRUE, 8, 0 },
	{ ARRAY_TAG, TRUE, 8, 0 },
	{ ARRAY_TAG, TRUE, 4, 0 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, TRUE, 0, 1 },
	{ NORMAL_TAG, TRUE, 0, 1 },
	{ NORMAL_TAG, FALSE, 0, 3 },
	{ ARRAY_TAG, TRUE, 8, 0 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 1 },
	{ NORMAL_TAG, FALSE, 0, 1 },
	{ NORMAL_TAG, FALSE, 8, 1 },
	{ NORMAL_TAG, FALSE, 0, 3 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 8, 1 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 1 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
};
static uint32_t* sourceSeqs[] = {
};
static GC_sourceSeqIndex frameSources[] = {
};
static struct GC_sourceLabel sourceLabels[] = {
};
static char* sourceNames[] = {
};
static struct GC_source sources[] = {
};
static char* atMLtons[] = {
	"@MLton",
	"--",
};
PRIVATE CPointer localCPointer[189];
PRIVATE Int8 localInt8[0];
PRIVATE Int16 localInt16[0];
PRIVATE Int32 localInt32[0];
PRIVATE Int64 localInt64[0];
PRIVATE Objptr localObjptr[168];
PRIVATE Real32 localReal32[0];
PRIVATE Real64 localReal64[5];
PRIVATE Word8 localWord8[3];
PRIVATE Word16 localWord16[0];
PRIVATE Word32 localWord32[6];
PRIVATE Word64 localWord64[7];
MLtonMain (8, 0xEE0BB45B, 168, TRUE, PROFILE_NONE, FALSE, F_0)
int main (int argc, char* argv[]) {
return (MLton_main (argc, argv));
}
